baseURL = "http://hanakno863.github.io/learn-docs"
languageCode = "ja"
title = "Learn Docs"
theme = "book"
# Book configuration
enableGitInfo = true

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.highlight]
    pygmentsUseClasses=true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[menu]
  [[menu.after]]
    name = "Github"
    url = "https://github.com/hnakano863/learn-docs"
    weight = 10

[params]
  BookMenuBundle = "/menu"
