baseURL = "http://hanakno863.github.io/learn-docs"
languageCode = "en-us"
title = "Learn Docs"
theme = "book"
BookMenuBundle = "/menu"

[markup]
  [markup.highlight]
    pygmentsUseClasses=true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
